name = "QuantileEffects"
uuid = "d36ccd49-ea39-409c-a324-14a05c2736d5"
authors = ["Caio Miguez <miguezcaio@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
